### ISSUE TITLE
 Support for Windows System Development

### ISSUE THREAD

**Issue by jkcs** [teocloud/teo-docs#4]
# Description
Currently, the handling of paths in `plugins\tableOfContents.mjs` and `scripts\generateToc.mjs` does not consider the Windows system.

Requesting a fix for this issue.

**Comment by victorteokw** [comment]
Hi @jkcs, could you fix this? It's quite simple, just add another slash in the regex

**Comment by victorteokw** [comment]
@jkcs, I've pushed to main, try it out. Fix on your own if it still doesn't work
